title: Innisfil Toastmasters
description: Non-profit community club - Where Leaders Are Made

url: http://innisfiltoastmasters.org
baseurl: https://innisfiltm.github.io/
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: index.html
  - title: About
    url: about
  - title: FAQ
    url: faq
  - title: Contact
    url: contact

social:
  github: innisfilTM
  twitter: InnisfilTM
  facebook: innisfiltoastmasters
  email: innisfilTM@gmail.com

google_analytics: "UA-158160891-1"
